#!/usr/bin/python3

import sys
from flashcard import *
from random import shuffle

def get_cards(input_file):
    with open(input_file) as f:
        return [
            #noun.guess_article() for noun in (
            noun.guess_reverse() for noun in (
                noun(line.strip()) for line in f
            )
        ]

    return []


input_file = sys.argv[1]
cards = get_cards(input_file)
shuffle(cards)

for card in cards:
    guess = input(card.text + ": " )
    if card.matches(guess):
        print("Correct!")
        input()
    else:
        print("Too bad! The correct answer was: " + card.back)
        sys.exit(1)

print("Well done!")
